### ISSUE TITLE
UIStatusBarStyle issue

### ISSUE THREAD

**Issue by burhanaksendir** [johnlui/SwiftNotice#3]
In my iPhone application built with Xcode 6.3.1 for iOS 8.3  I set 

override func preferredStatusBarStyle() -> UIStatusBarStyle {
        return UIStatusBarStyle.LightContent
 }

When i use this function  self.infoNotice("Info")
  the status bar is still black against
How can I resolve this issue ?

Kind Regards,

**Comment by johnlui** [comment]
This may be a bug. I just hide the UIView but did not make UIWindow disappear. I will fix it soon, tanks for your feedback.

**Comment by johnlui** [comment]
Sorry I made a mistake about your problem. This issue might not caused by SwiftNotice.

If you want to change style of Status Bar, you can do 2 steps:
1. add a key "View controller-based status bar appearance" in info panel and set the value to NO.
2. run "UIApplication.sharedApplication().statusBarStyle = UIStatusBarStyle.LightContent" anywhere you want

**Comment by burhanaksendir** [comment]
You are a legend. Thanks a lot! This worked like a charm!
